config/routes.rb
Rails.application.routes.draw do
  resources :missions
  resources :listings do
    resources :bookings do
      member do
        get :cancel
      end
    end
    resources :reservations do
      member do
        get :cancel
      end
    end
  end
  root "home#show"
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :missions, dependent: :destroy

  before_create do
    self.title = Faker::Fantasy::Tolkien.location unless self.title.present?
    self.address = Faker::Address.full_address unless self.address.present?
    self.description = Faker::Lorem.paragraph unless self.description.present?
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :address, :description, :num_rooms)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.haml
= simple_form_for @listing, html: { class: "mt-6" } do |f|
  = f.input :title
  = f.input :description
  = f.input :address
  = f.input :num_rooms

  .sm:col-span-2.sm:flex.sm:justify-end.space-x-4
    = button_to "Back", listings_path, class: "my-2 bg-blue-300 hover:bg-blue-700 text-white font-bold text-sm py-2 px-4 rounded"
    = f.button :submit, "Envoyer", type: :submit

app/views/listings/edit.html.haml
.w-full.bg-white.py-24.sm:py-32
  .mx-auto.max-w-7xl.px-6.lg:px-8
    .mx-auto.max-w-2xl.text-center
      %h2.text-3xl.font-bold.tracking-tight.text-gray-900.sm:text-4xl Listings
      %p.mt-2.text-lg.leading-8.text-gray-600 Edit listing

  .mx-auto.max-w-3xl.px-6.lg:px-8
    = render 'form'

app/views/listings/index.html.haml
.w-full.bg-white.py-24.sm:py-32
  .mx-auto.max-w-7xl.px-6.lg:px-8
    .mx-auto.max-w-2xl.text-center
      %h2.text-3xl.font-bold.tracking-tight.text-gray-900.sm:text-4xl Listings
      %p.mt-2.text-lg.leading-8.text-gray-600 List of our current listings
    .mx-auto.mt-16.grid.max-w-2xl.auto-rows-fr.grid-cols-1.gap-8.sm:mt-20.lg:mx-0.lg:max-w-none.lg:grid-cols-3

      - @listings.each do |listing|
        .flex.flex-col
          .relative.isolate.flex.h-full.flex-col.justify-end.overflow-hidden.rounded-2xl.bg-gray-900.px-8.pb-8.pt-80.sm:pt-48.lg:pt-80
            = image_tag "listings/#{rand(1..6)}.jpg", class: "absolute inset-0 -z-10 h-full w-full object-cover"
            .absolute.inset-0.-z-10.bg-gradient-to-t.from-gray-900{:class => "via-gray-900/40"}
            .absolute.inset-0.-z-10.rounded-2xl.ring-1.ring-inset{:class => "ring-gray-900/10"}
            .flex.flex-wrap.items-center.gap-y-1.overflow-hidden.text-sm.leading-6.text-gray-300
              %time.mr-8= listing.created_at.to_fs(:short)
            %h3.mt-3.text-lg.font-semibold.leading-6.text-white
              = link_to listing do
                %span.absolute.inset-0
                = listing.title
            .mt-3.text-sm.leading-6.text-white
              = link_to listing do
                %span.absolute.inset-0
                = listing.address
            .mt-3.text-sm.leading-6.text-white
              = link_to listing do
                %span.absolute.inset-0
                = listing.num_rooms
                rooms

          %span.isolate.inline-flex.rounded-md.mt-3
            = button_to "Edit", edit_listing_path(listing), method: :get, class: "relative inline-flex items-center rounded-l-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-10"
            = button_to "Destroy", listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "relative -ml-px inline-flex items-center rounded-r-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-10"

    .flex.flex-row.mt-16
      = button_to "New Listing", new_listing_path, method: :get, class: "px-3.5 py-2.5 rounded-md bg-indigo-600 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"

app/views/listings/new.html.haml
.w-full.bg-white.py-24.sm:py-32
  .mx-auto.max-w-7xl.px-6.lg:px-8
    .mx-auto.max-w-2xl.text-center
      %h2.text-3xl.font-bold.tracking-tight.text-gray-900.sm:text-4xl Listings
      %p.mt-2.text-lg.leading-8.text-gray-600 Create a new listing

  .mx-auto.max-w-3xl.px-6.lg:px-8
    = render 'form'

app/views/listings/show.html.haml
.bg-white.px-6.py-24.sm:py-32.lg:px-8.w-full
  .mx-auto.max-w-2xl.text-center
    %p.text-base.font-semibold.leading-7.text-indigo-600 Listing
    %h2.mt-2.text-4xl.font-bold.tracking-tight.text-gray-900.sm:text-6xl= @listing.title
    %p.mt-6.text-lg.leading-8.text-gray-600
      = @listing.description
      %br
      = @listing.address

  .grid.grid-cols-2.gap-4
    .px-4.sm:px-6.lg:px-8.mt-16
      .sm:flex.sm:items-center
        .sm:flex-auto
          %h1.text-base.font-semibold.leading-6.text-gray-900 Bookings
        .mt-4.sm:ml-16.sm:mt-0.sm:flex-none
          = link_to "Add a booking", new_listing_booking_path(@listing), class: "block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"

      - if @listing.bookings.any?
        .mt-8.flow-root
          .-mx-4.-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
            .inline-block.min-w-full.py-2.align-middle.sm:px-6.lg:px-8
              %table.min-w-full.divide-y.divide-gray-300
                %thead
                  %tr
                    %th.pl-4.pr-3.text-left.text-sm.font-semibold.text-gray-900.sm:pl-0{:class => "py-3.5", :scope => "col"} Start date
                    %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} End date
                    %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} Status
                    %th.relative.pl-3.pr-4.sm:pr-0{:class => "py-3.5", :scope => "col"}
                      %span.sr-only Edit
                %tbody.divide-y.divide-gray-200.bg-white
                  - @listing.bookings.each do |booking|
                    %tr
                      %td.whitespace-nowrap.py-4.pl-4.pr-3.text-sm.sm:pl-0
                        = booking.start_date
                      %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500
                        = booking.end_date
                      %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500
                        %span.inline-flex.rounded-full.px-2.text-xs.font-semibold.leading-5{ class: booking.canceled? ? "bg-red-100 text-red-800" : "bg-green-100 text-green-800" }
                          = booking.state.upcase
                      %td.relative.whitespace-nowrap.py-4.pl-3.pr-4.text-right.text-sm.font-medium.sm:pr-0
                        = link_to "Cancel", cancel_listing_booking_path(@listing, booking), class: "text-red-600 hover:text-red-900" unless booking.canceled?
                        = link_to "Edit", edit_listing_booking_path(@listing, booking), class: "text-indigo-600 hover:text-indigo-900"
                        = link_to "Show", listing_booking_path(@listing, booking), class: "text-indigo-600 hover:text-indigo-900"
                        = link_to "Destroy", [@listing, booking], data: { turbo_method: :delete, confirm: 'Are you sure?' }, class: "text-indigo-600 hover:text-indigo-900"

    .px-4.sm:px-6.lg:px-8.mt-16
      .sm:flex.sm:items-center
        .sm:flex-auto
          %h1.text-base.font-semibold.leading-6.text-gray-900 Reservations
        .mt-4.sm:ml-16.sm:mt-0.sm:flex-none
          = link_to "Add a reservation", new_listing_reservation_path(@listing), class: "block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"

      - if @listing.reservations.any?
        .mt-8.flow-root
          .-mx-4.-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
            .inline-block.min-w-full.py-2.align-middle.sm:px-6.lg:px-8
              %table.min-w-full.divide-y.divide-gray-300
                %thead
                  %tr
                    %th.pl-4.pr-3.text-left.text-sm.font-semibold.text-gray-900.sm:pl-0{:class => "py-3.5", :scope => "col"} Start date
                    %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} End date
                    %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} Status
                    %th.relative.pl-3.pr-4.sm:pr-0{:class => "py-3.5", :scope => "col"}
                      %span.sr-only Edit
                %tbody.divide-y.divide-gray-200.bg-white
                  - @listing.reservations.each do |reservation|
                    %tr
                      %td.whitespace-nowrap.py-4.pl-4.pr-3.text-sm.sm:pl-0
                        = reservation.start_date
                      %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500
                        = reservation.end_date
                      %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500
                        %span.inline-flex.rounded-full.px-2.text-xs.font-semibold.leading-5{ class: reservation.canceled? ? "bg-red-100 text-red-800" : "bg-green-100 text-green-800" }
                          = reservation.state.upcase
                      %td.relative.whitespace-nowrap.py-4.pl-3.pr-4.text-right.text-sm.font-medium.sm:pr-0
                        = link_to "Cancel", cancel_listing_reservation_path(@listing, reservation), class: "text-red-600 hover:text-red-900" unless reservation.canceled?
                        = link_to "Edit", edit_listing_reservation_path(@listing, reservation), class: "text-indigo-600 hover:text-indigo-900"
                        = link_to "Show", listing_reservation_path(@listing, reservation), class: "text-indigo-600 hover:text-indigo-900"
                        = link_to "Destroy", [@listing, reservation], data: { turbo_method: :delete, confirm: 'Are you sure?' }, class: "text-indigo-600 hover:text-indigo-900"

  - if @listing.missions.any?
    .px-4.sm:px-6.lg:px-8.mt-16
      .sm:flex.sm:items-center
        .sm:flex-auto
          %h1.text-base.font-semibold.leading-6.text-gray-900 Missions
        .mt-4.sm:ml-16.sm:mt-0.sm:flex-none
      .mt-8.flow-root
        .-mx-4.-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
          .inline-block.min-w-full.py-2.align-middle.sm:px-6.lg:px-8
            %table.min-w-full.divide-y.divide-gray-300
              %thead
                %tr
                  %th.pl-4.pr-3.text-left.text-sm.font-semibold.text-gray-900.sm:pl-0{:class => "py-3.5", :scope => "col"} Type
                  %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} Date
                  %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} Price
                  %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} State
                  -# %th.relative.pl-3.pr-4.sm:pr-0{:class => "py-3.5", :scope => "col"}
                  -#   %span.sr-only Edit
              %tbody.divide-y.divide-gray-200.bg-white
                - @listing.missions.each do |mission|
                  %tr
                    %td.whitespace-nowrap.py-4.pl-4.pr-3.text-sm.sm:pl-0
                      = mission.mission_type
                    %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500
                      = mission.date
                    %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500
                      = mission.price
                      = mission.price_currency
                    %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500
                      %span.inline-flex.rounded-full.px-2.text-xs.font-semibold.leading-5{ class: mission.canceled? ? "bg-red-100 text-red-800" : "bg-green-100 text-green-800" }
                        = mission.state.upcase
                    -# %td.relative.whitespace-nowrap.py-4.pl-3.pr-4.text-right.text-sm.font-medium.sm:pr-0
                    -#   = link_to "Cancel", cancel_listing_booking_path(@listing, booking), class: "text-red-600 hover:text-red-900"